### ISSUE TITLE
NPE after rendering nearby Citizens NPC

### ISSUE THREAD

**Issue by kronnox** [iso2013/MultiLineAPI#24]
_(mc-version : 1.11.2; MultiLineAPI 1.2.6; ProtocolLib v4.1.0; Citizens v2.0.21-SNAPSHOT)_

As soon as you walk near an NPC, MultiLineAPI throws the following NullPointerException:

`[12:46:01 ERROR]: [MultiLineAPI] Unhandled exception occured in onPacketSending(PacketEvent) for MultiLineAPI
java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.canSee(CraftPlayer.java:953) ~[spigot.jar:git-Spigot-4741400-c1aa859]
	at net.blitzcube.mlapi.listener.PacketHandler.spawnPlayer(PacketHandler.java:84) ~[MultiLineAPI-1.2.6.jar:?]
	at net.blitzcube.mlapi.listener.PacketHandler.onPacketSending(PacketHandler.java:50) ~[MultiLineAPI-1.2.6.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.1.0-b325]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.1.0-b325]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1090) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.citizensnpcs.nms.v1_11_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:45) [Citizens.jar:?]
	at net.minecraft.server.v1_11_R1.EntityTracker.updatePlayers(EntityTracker.java:200) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:831) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-4741400-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-4741400-c1aa859]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[12:46:01 ERROR]: Parameters: 
  net.minecraft.server.v1_11_R1.PacketPlayOutNamedEntitySpawn@3818fe99[
    a=180
    b=4f1d0d9f-993d-243e-ac8e-9a2b73abef1f
    c=-236.1291
    d=69.0
    e=-138.5296
    f=-64
    g=0
    h=net.minecraft.server.v1_11_R1.DataWatcher@63d1ebfd
    i=<null>
  ]
`

**Comment by jacobsandersen** [comment]
MultiLineAPI is currently being rewritten to not use embedded entities at all, so this error will go away.
